[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_meme_alchemy = "GCmY5vbNkFNdM5ofYcNHnJ8ivZNzHLVP3vEx6vUbYdFQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "/Users/kevin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
